Repository bitcoin-dot-org/Bitcoin.org, pull requests merged in 2018-05, with the labels that each got.

#2322 blog: Add 'Test New Bitcoin.org Design' post
  _posts/2018-05-01-test-the-new-site-design.md
Labels: Redesign

#2092 Added developer documentation for new p2p protocol message types
  _autocrossref.yaml
  _config.yml
  _data/devdocs/en/references/p2p_networking.md
  _includes/references.md
Labels: Merge Scheduled

#2338 Update events page
  _events.yml
Labels: Events, Merge Scheduled

#2098 Improved the P2SH documentation
  _data/devdocs/en/guides/transactions.md
  _includes/references.md
Labels: Under Review

#2346 Remove Bitcoin Wallet for BlackBerry OS (no longer supported)
  Makefile
  _platforms/mobile/blackberry.html
  _sass/_wallets-menu.scss
  _templates/development.html
  _translations/ar.yml
  _translations/bg.yml
  _translations/da.yml
  _translations/de.yml
  _translations/el.yml
  _translations/en.yml
  _translations/es.yml
  _translations/fa.yml
  _translations/fr.yml
  _translations/hi.yml
  _translations/hu.yml
  _translations/id.yml
  _translations/it.yml
  _translations/ja.yml
  _translations/ko.yml
  _translations/nl.yml
  _translations/pl.yml
  _translations/pt_BR.yml
  _translations/ro.yml
  _translations/ru.yml
  _translations/sl.yml
  _translations/sv.yml
  _translations/tr.yml
  _translations/uk.yml
  _translations/zh_CN.yml
  _translations/zh_TW.yml
  _wallets/bitcoinwallet.md
  quality-assurance/schemas/wallets.yaml
Labels: Merge Scheduled, Wallets

#2089 Added CoinSpot to Australian Exchanges
  _templates/exchanges.html
Labels: Changes Requested

#2128 Fix input parameter from Address to TXID for getmempool[entry][descedants][ancestors]
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/getmempoolancestors.md
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/getmempooldescendants.md
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/getmempoolentry.md
Labels: Under Review

#2318 GetInfo was removed in 0.16.0
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/getinfo.md
Labels: Under Review

#2321 update breadwallet => BRD
  _translations/ar.yml
  _translations/bg.yml
  _translations/da.yml
  _translations/de.yml
  _translations/el.yml
  _translations/en.yml
  _translations/es.yml
  _translations/fa.yml
  _translations/fr.yml
  _translations/hi.yml
  _translations/hu.yml
  _translations/id.yml
  _translations/it.yml
  _translations/ja.yml
  _translations/ko.yml
  _translations/nl.yml
  _translations/pl.yml
  _translations/pt_BR.yml
  _translations/ro.yml
  _translations/ru.yml
  _translations/sl.yml
  _translations/sv.yml
  _translations/tr.yml
  _translations/uk.yml
  _translations/zh_CN.yml
  _translations/zh_TW.yml
  _wallets/brd.md
  en/bitcoin-core/features/privacy.md
  img/screenshots/brd.png
  img/screenshots/breadwallet.png
  img/wallet/brd.png
  img/wallet/breadwallet.png
Labels: Under Review

#2280 rescanblockchain.md
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/rescanblockchain.md
Labels: Under Review

#2261 Update getinfo.md
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/getinfo.md
Labels: Under Review

#2353 wallets: Optimize images for BRD
  img/screenshots/brd.png
  img/wallet/brd.png
Labels: Wallets

#2354 subsequent redesign changes
  _includes/layout/base/wallets-list.html
  _sass/_wallets.scss
Labels: Redesign

#2256 Update getrawmempool.md
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/getrawmempool.md
Labels: Under Review

#2355 full-node: Change Ubuntu version to 16.04
  en/full-node.md
Labels: Dev Docs

#2356 full-node: Add sync requirement for using BitNodes
  en/full-node.md
Labels: Merge Scheduled

#2357 Remove dead links to exchanges
  _templates/exchanges.html
Labels: Merge Scheduled

#2358 contributing: Fix broken link
  docs/contributing-to-developer-documentation.md
Labels: Merge Scheduled

#2359 en: Remove broken link to Lighthouse app
  _translations/en.yml
Labels: Merge Scheduled

#2292 Added ThroughBit to the List of Indian Exchanges
  _templates/exchanges.html
Labels: Merge Scheduled

#2351 Add Coinmama to International exchanges
  _templates/exchanges.html
Labels: Merge Scheduled

#2369 exchanges: Add OmniTrade
  _templates/exchanges.html
Labels: Merge Scheduled

#2370 en: Remove broken link
  _translations/en.yml
Labels: Merge Scheduled

#2371 full-node: Remove '-daemon' param for Windows instrux
  en/full-node.md
Labels: Merge Scheduled

#2374 block_chain: Fix typographical error in docs
  _data/devdocs/en/guides/block_chain.md
Labels: Merge Scheduled

#2388 Corrected a following to subsequent
  _data/devdocs/en/guides/block_chain.md
Labels: Dev Docs, Merge Scheduled

#2386 Replace Biteasy with BlockCypher
  _includes/references.md
  _templates/resources.html
  _translations/ar.yml
  _translations/bg.yml
  _translations/da.yml
  _translations/de.yml
  _translations/el.yml
  _translations/en.yml
  _translations/es.yml
  _translations/fa.yml
  _translations/fr.yml
  _translations/hi.yml
  _translations/hu.yml
  _translations/id.yml
  _translations/it.yml
  _translations/ja.yml
  _translations/ko.yml
  _translations/nl.yml
  _translations/pl.yml
  _translations/pt_BR.yml
  _translations/ro.yml
  _translations/ru.yml
  _translations/sl.yml
  _translations/sv.yml
  _translations/tr.yml
  _translations/uk.yml
  _translations/zh_CN.yml
  _translations/zh_TW.yml
Labels: Merge Scheduled

#2385 resources: Drop Airbitz as a 'Merchant' link
  _templates/resources.html
Labels: Merge Scheduled

#2384 Remove coinapult wallet
  _translations/da.yml
  _translations/de.yml
  _translations/en.yml
  _translations/es.yml
  _translations/hu.yml
  _translations/it.yml
  _translations/pl.yml
  _translations/pt_BR.yml
  _translations/ru.yml
  _translations/sv.yml
  _translations/tr.yml
  _translations/uk.yml
  _wallets/coinapult.md
  img/screenshots/coinapult.png
  img/wallet/coinapult.png
Labels: Merge Scheduled, Wallets

#2383 Update transparency score on mature wallets
  _wallets/coinspace.md
  _wallets/digitalbitbox.md
  _wallets/keepkey.md
  _wallets/ledgernanos.md
Labels: Merge Scheduled, Wallets
