Repository bitcoin-dot-org/Bitcoin.org, pull requests merged in 2018-08, with the labels that each got.

#2545 Added Argentinian exchange
  _templates/exchanges.html
Labels: Exchanges, Merge Scheduled

#2537 GetBlock documentation update required for the verbosity parameter.
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/getblock.md
Labels: Dev Docs, Merge Scheduled

#2546 Fix for #2219: Add deprecated to Estimate Fee in developer reference
  _data/devdocs/en/bitcoin-core/rpcs/quick-reference.md
Labels: Dev Docs, Merge Scheduled

#2547 Fix for #2219: Add deprecated to estimatefee and estimatedpriority
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/estimatepriority.md
Labels: Dev Docs, Merge Scheduled

#2570 _config: Add redirects; languages without buy page
  _config.yml
Labels: Merge Scheduled

#2576 [Resources] Add more recent Bitcoin Documentary links
  _templates/resources.html
Labels: Merge Scheduled

#2592 Update Events Calendar
  _events.yml
Labels: Merge Scheduled

#2595 Update German Translation
  _translations/de.yml
Labels: Translations

#2596 Update Serbian Translation
  _config.yml
  _templates/about-us.html
  _translations/sr.yml
Labels: Translations

#2604 about-us: Change alias to real name
  _templates/about-us.html
Labels: Merge Scheduled

#2594 Add page to help users avoid scams
  _includes/layout/base/footer-menu.html
  _templates/scams.html
  _translations/en.yml
Labels: Merge Scheduled

#2607 index: Shorten text to remove wrap
  _includes/templates/index.html
Labels: Merge Scheduled

#2608 scams: Add translation string
  _templates/scams.html
  _translations/en.yml
Labels: Merge Scheduled

#2609 sidebar: Change 'View Topics' to 'View All'
  _layouts/sidebar.html
Labels: Merge Scheduled

#2613 exchanges: Change name, Bitcoin Indonesia > Indodax
  _templates/exchanges.html
Labels: Exchanges, Merge Scheduled

#2622 index: Drop Bitcoin.org Anniversary Note
  _includes/templates/index.html
Labels: Merge Scheduled
