Repository bitcoin-dot-org/Bitcoin.org, pull requests merged in 2019-09, with the labels that each got.

#3093 helper-step-2: Drop overridden heading
  _includes/layout/base/helper-step-2.html
Labels: Merge Scheduled

#3100 Update Events Page
  _events.yml
Labels: Events, Merge Scheduled

#3103 Cleanup unused wallet assets
  img/screenshots/coinbase.png
  img/screenshots/ninki.png
  img/screenshots/xapo.png
  img/wallet/airbitzwallet.png
  img/wallet/arcbit.png
  img/wallet/coinbase.png
  img/wallet/ninki.png
  img/wallet/simplebitcoinwallet.png
  img/wallet/xapo.png
Labels: Merge Scheduled, Wallets

#3109 en: Add missing meta description to Wallet wizard
  _translations/en.yml
Labels: Merge Scheduled, Wallets

#3104 Add guidance for wallet features
  docs/managing-wallets.md
Labels: Merge Scheduled, Wallets

#3106 Add optional indicator to wallet selection wizard
  _includes/layout/base/helper-step-3.html
  _includes/layout/base/helper-step-4.html
  _translations/en.yml
Labels: Merge Scheduled, Wallets

#3112 Require bug reporting method
  docs/managing-wallets.md
Labels: Merge Scheduled, Wallets

#3122 Update Events Page
  _events.yml
Labels: Events, Merge Scheduled

#3117 Remove BitGo and Edge Wallet
  _translations/ar.yml
  _translations/bg.yml
  _translations/da.yml
  _translations/de.yml
  _translations/el.yml
  _translations/en.yml
  _translations/es.yml
  _translations/fa.yml
  _translations/fr.yml
  _translations/hi.yml
  _translations/hu.yml
  _translations/id.yml
  _translations/it.yml
  _translations/ja.yml
  _translations/ko.yml
  _translations/nl.yml
  _translations/pl.yml
  _translations/pt_BR.yml
  _translations/ro.yml
  _translations/ru.yml
  _translations/sl.yml
  _translations/sr.yml
  _translations/sv.yml
  _translations/tr.yml
  _translations/uk.yml
  _translations/zh_CN.yml
  _translations/zh_TW.yml
  _wallets/bitgo.md
  _wallets/edgewallet.md
  img/screenshots/bitgo.png
  img/screenshots/edgewalletandroid.png
  img/screenshots/edgewalletios.png
  img/wallet/bitgo.png
  img/wallet/edgewallet.png
Labels: Merge Scheduled, Wallets

#3116 bitcoin-paper: Add Norwegian translation, update Thai translation
  _templates/bitcoin-paper.html
  files/bitcoin-paper/bitcoin_no.pdf
  files/bitcoin-paper/bitcoin_th.pdf
Labels: Merge Scheduled, Translations

#3126 bitcoin-paper: s/Bokmal/Norsk (Bokmal)
  _templates/bitcoin-paper.html
Labels: Merge Scheduled, Translations

#3127 en: Drop reference to reddit accepting bitcoin
  _translations/en.yml
Labels: Merge Scheduled

#3118 Review wallet descriptions for superlatives, grammatical issues and punctuation mistakes
  _translations/en.yml
Labels: Merge Scheduled, Wallets

#3120 blog: Add 'A New Design for Wallet Pages'
  _posts/2019-09-24-new-design-for-wallet-pages.md
Labels: Merge Scheduled, Redesign, Wallets

#3128 wallet-selector: Do not override anchor link style
  _sass/_wallet-selector.scss
Labels: Wallets
