Repository bitcoin-dot-org/Bitcoin.org, pull requests merged in 2019-05, with the labels that each got.

#2887 Adds Coldcard
  _translations/en.yml
  _wallets/coldcard.md
  img/screenshots/coldcard.png
  img/wallet/coldcard.png
Labels: Merge Scheduled, Wallets

#2945 Bitcoin Core 0.18.0
  _releases/v0.18.0.md
Labels: Core

#2947 Fix broken links on Download page
  Makefile
  _sass/screen.scss
  _templates/download.html
Labels: Core, Merge Scheduled

#2953 en: Fix typos
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/getdifficulty.md
  _data/devdocs/en/bitcoin-core/rpcs/rpcs/verifychain.md
  _data/devdocs/en/guides/mining.md
  _translations/en.yml
Labels: Merge Scheduled

#2940 add ChainNode.com to the "Bitcoin community" page
  _templates/community.html
Labels: Merge Scheduled

#2956 community: Add 'Bitcoin Association of Northern Ireland'
  _templates/community.html
Labels: Merge Scheduled

#2959 wallets-menu: Upcase selected item
  _sass/_wallets-menu.scss
Labels: Bug, Merge Scheduled, Wallets

#2954 Bitcoin paper: Add Ukrainian translation
  _templates/bitcoin-paper.html
  files/bitcoin-paper/bitcoin_uk.pdf
Labels: Merge Scheduled, Translations

#2974 Update Events Page
  _events.yml
Labels: Events, Merge Scheduled

#2951 Add: Binance SG, Binance UG & Binance JE
  _templates/exchanges.html
  img/flags/UG.png
  img/flags/UG.svg
Labels: Exchanges, Merge Scheduled

#2985 translations: Update Japanese Translation
  _translations/ja.yml
Labels: Merge Scheduled, Translations

#2987 translations: Update Indonesian Translation
  _translations/id.yml
Labels: Merge Scheduled, Translations

#2988 translations: Update Italian Translation
  _translations/it.yml
Labels: Merge Scheduled, Translations

#2989 translations: Update Hungarian Translation
  _config.yml
  _templates/development.html
  _translations/hu.yml
Labels: Merge Scheduled, Translations

#2983 download: Replace ppa with snap
  _sass/screen.scss
  _templates/download.html
  img/os/med_snap.png
  img/os/med_snap.svg
  img/os/med_ubuntu.png
  img/os/med_ubuntu.svg
Labels: Core, Merge Scheduled

#2991 full-node: Update instructions
  en/full-node.md
  img/full-node/en-dash-bitcoin-qt.png
  img/full-node/en-dash-term.png
Labels: Core, Merge Scheduled

#2995 community: Drop 'Bitcoin Foundation Ukraine'
  _templates/community.html
Labels: Merge Scheduled
